export const CHANGE_BASEMAP = 'CHANGE_BASEMAP';

export const TRACE_FEATURE = 'TRACE_FEATURE';
export const CLEAR_TRACE = 'CLEAR_TRACE';

export const GET_FEATURES = 'GET_FEATURES';
export const ADD_FEATURE = 'ADD_FEATURE';
export const REMOVE_FEATURE = 'REMOVE_FEATURE';
export const REMOVE_ALL_FEATURES = 'REMOVE_ALL_FEATURES';
